### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Jaimi5** [secomms/CortexM4Ethereum#1]
Hello! 

I am trying to compile your code. However, I think that all the .h files are missing.

Furthermore, nice job with your paper! Hope to use it for new investigations!
Thanks!

Joan

**Comment by secommsadmin** [comment]
Dear Joan,

thank you for your interest in our work!
In these days we have checked the repository and confirmed the problem you noticed, thank you for spotting it.
Now, the source package included in the repository should be complete, please let us know.

Best,
Marco


Da: Joan Miquel Solé ***@***.***>
Inviato: mercoledì 26 ottobre 2022 11:26
A: secomms/CortexM4Ethereum ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [secomms/CortexM4Ethereum] Missing files (Issue #1)


Hello!

I am trying to compile your code. However, I think that all the .h files are missing.

Furthermore, nice job with your paper! Hope to use it for new investigations!
Thanks!

Joan
